/**: # wildcard for namespace
  joint_saturation_limiter_layer:
    ros__parameters:
      joint_limits:
        axis:
          has_position_limits: true
          min_position: -1.0
          max_position: 1.0
          has_velocity_limits: true
          max_velocity: 0.5